FROM python:3.10.8-bullseye
RUN pip3 install fastapi==0.85.1 uvicorn==0.19.0 orjson==3.8.0 ujson==5.5.0
WORKDIR /src
COPY app.py .
COPY start_uvicorn.sh .
COPY test_json_1MB.json .
EXPOSE 8000
ENV WORKERS=1
ENTRYPOINT /src/start_uvicorn.sh