FROM python:3.10.8-bullseye
RUN python -m pip install --upgrade pip && pip3 install fastapi==0.85.1 uvicorn==0.19.0 orjson==3.8.0 ujson==5.5.0
WORKDIR /src
COPY app.py .
COPY test_json_1MB.json .
EXPOSE 8000
ENTRYPOINT ["uvicorn", "--workers=1", "app:app"]
